### ISSUE TITLE
lecture 01 typo

### ISSUE THREAD

**Issue by drwadu** [knowsys/TheoLog#64]
change \item 1976: Computerbeweis **der** Vier-Farben-Problems (Appel \& \ghost{Haken)}\pause to \item 1976: Computerbeweis **des** Vier-Farben-Problems (Appel \& \ghost{Haken)}\pause 

in https://www.youtube.com/watch?v=D4Df-NKaFRs: Folie 5 von 11

**Comment by mkroetzsch** [comment]
Thanks, fixed (in the slide sources, not in the video).
